[2022-02-04 10:57:22.011435]Traceback (most recent call last):
  File ".\server.py", line 87, in recv_data
    bytes = self.socket.recv(4096)  # 我们这里只做一个简单的服务端框架，只做粘包不做分包处理。
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[2022-02-04 10:59:46.187121]Traceback (most recent call last):
  File ".\server.py", line 87, in recv_data
    bytes = self.socket.recv(4096)  # 我们这里只做一个简单的服务端框架，只做粘包不做分包处理。
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[2022-02-04 10:59:46.191122]Traceback (most recent call last):
  File ".\server.py", line 87, in recv_data
    bytes = self.socket.recv(4096)  # 我们这里只做一个简单的服务端框架，只做粘包不做分包处理。
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[2022-02-04 10:59:46.950689]Traceback (most recent call last):
  File ".\server.py", line 87, in recv_data
    bytes = self.socket.recv(4096)  # 我们这里只做一个简单的服务端框架，只做粘包不做分包处理。
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[2022-02-04 11:06:01.048300]Traceback (most recent call last):
  File ".\server.py", line 87, in recv_data
    bytes = self.socket.recv(4096)  # 我们这里只做一个简单的服务端框架，只做粘包不做分包处理。
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[2022-02-04 11:45:55.833448]Traceback (most recent call last):
  File ".\server.py", line 37, in __init__
    self.listener.bind((ip, port))  # 绑定ip、端口
OSError: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
[2022-02-04 11:46:43.411988]Traceback (most recent call last):
  File ".\server.py", line 95, in recv_data
    self.deal_data(bytes)
  File ".\server.py", line 149, in deal_data
    protocol = json.loads(str_protocol)
  File "D:\Program Files (x86)\anaconda\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files (x86)\anaconda\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files (x86)\anaconda\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-02-04 11:48:26.520571]Traceback (most recent call last):
  File ".\server.py", line 87, in recv_data
    bytes = self.socket.recv(4096)  # 我们这里只做一个简单的服务端框架，只做粘包不做分包处理。
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[2022-02-04 11:50:28.010541]Traceback (most recent call last):
  File ".\server.py", line 87, in recv_data
    bytes = self.socket.recv(4096)  # 我们这里只做一个简单的服务端框架，只做粘包不做分包处理。
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[2022-02-04 11:54:16.390043]Traceback (most recent call last):
  File ".\server.py", line 87, in recv_data
    bytes = self.socket.recv(4096)  # 我们这里只做一个简单的服务端框架，只做粘包不做分包处理。
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[2022-02-04 11:56:34.591160]Traceback (most recent call last):
  File ".\server.py", line 87, in recv_data
    bytes = self.socket.recv(4096)  # 我们这里只做一个简单的服务端框架，只做粘包不做分包处理。
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
